"""add unique constraint to client cnpj

Revision ID: 452ebc16bf35
Revises: 
Create Date: 2026-06-03 19:57:27.511504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452ebc16bf35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_tenant_id_cnpj_key'), 'clients', type_='unique')
    op.create_unique_constraint('uq_tenant_cnpj', 'clients', ['tenant_id', 'cnpj'])
    op.create_foreign_key(None, 'clients', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint('uq_tenant_cnpj', 'clients', type_='unique')
    op.create_unique_constraint(op.f('clients_tenant_id_cnpj_key'), 'clients', ['tenant_id', 'cnpj'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
