"""Adiciona tabela fiscal_deadlines

Revision ID: 52b1b0ed4739
Revises: b2f36fb1a708
Create Date: 2026-06-08 21:03:36.652261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b1b0ed4739'
down_revision: Union[str, Sequence[str], None] = 'b2f36fb1a708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscal_deadlines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_deadlines_tenant_id'), 'fiscal_deadlines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fiscal_deadlines_tenant_id'), table_name='fiscal_deadlines')
    op.drop_table('fiscal_deadlines')
    # ### end Alembic commands ###
