"""add ativo field to clients

Revision ID: b2f36fb1a708
Revises: 452ebc16bf35
Create Date: 2026-06-04 14:37:33.905681

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2f36fb1a708"
down_revision: Union[str, Sequence[str], None] = "452ebc16bf35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adiciona a coluna com server_default='true', o que faz os clientes antigos ficarem como 'ativo'
    op.add_column(
        "clients",
        sa.Column(
            "ativo", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "ativo")
    # ### end Alembic commands ###
