"""create tax_deadlines table

Revision ID: d543a3bf9f08
Revises: f7cd6446f0cc
Create Date: 2026-06-11 20:09:11.092774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd543a3bf9f08'
down_revision: Union[str, Sequence[str], None] = 'f7cd6446f0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=False),
    sa.Column('is_monthly', sa.Boolean(), nullable=True),
    sa.Column('reference_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_deadlines_id'), 'tax_deadlines', ['id'], unique=False)
    op.create_index(op.f('ix_tax_deadlines_title'), 'tax_deadlines', ['title'], unique=False)
    op.alter_column('clients', 'tipo_pessoa',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'PJ'::character varying"))
    op.alter_column('clients', 'regime_tributario',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('clients', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_clients_tenant_id'), 'clients', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('clients_tenant_id_fkey'), 'clients', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('clients_tenant_id_fkey'), 'clients', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_clients_tenant_id'), table_name='clients')
    op.alter_column('clients', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('clients', 'regime_tributario',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('clients', 'tipo_pessoa',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'PJ'::character varying"))
    op.drop_index(op.f('ix_tax_deadlines_title'), table_name='tax_deadlines')
    op.drop_index(op.f('ix_tax_deadlines_id'), table_name='tax_deadlines')
    op.drop_table('tax_deadlines')
    # ### end Alembic commands ###
