"""Adiciona campos PF e torna PJ opcional v2

Revision ID: f7cd6446f0cc
Revises: 52b1b0ed4739
Create Date: 2026-06-10 19:40:06.052951

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f7cd6446f0cc"
down_revision: Union[str, Sequence[str], None] = "52b1b0ed4739"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 1. Adiciona tipo_pessoa com valor padrão para os clientes antigos
    op.add_column(
        "clients",
        sa.Column("tipo_pessoa", sa.String(), nullable=False, server_default="PJ"),
    )

    # 2. Adiciona os campos de Pessoa Física
    op.add_column("clients", sa.Column("nome", sa.String(), nullable=True))
    op.add_column("clients", sa.Column("cpf", sa.String(), nullable=True))

    # 3. Torna Razão Social e CNPJ opcionais
    op.alter_column(
        "clients", "razao_social", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "clients", "cnpj", existing_type=sa.VARCHAR(length=18), nullable=True
    )

    # 4. Remove a restrição de unicidade do CNPJ
    # O nome 'uq_tenant_cnpj' pode variar, use o que o Alembic gerou
    op.drop_constraint(op.f("uq_tenant_cnpj"), "clients", type_="unique")

    # 5. APENAS SE VOCÊ REALMENTE NÃO QUER MAIS O CREATED_AT NO BANCO:
    op.drop_column("clients", "created_at")
    # (Se você ainda usa created_at no model, comente a linha acima)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("clients_tenant_id_fkey"),
        "clients",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_clients_tenant_id"), table_name="clients")
    op.create_unique_constraint(
        op.f("uq_tenant_cnpj"),
        "clients",
        ["tenant_id", "cnpj"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "clients",
        "ativo",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "clients",
        "regime_tributario",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "clients", "cnpj", existing_type=sa.VARCHAR(length=18), nullable=False
    )
    op.alter_column(
        "clients", "razao_social", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("clients", "cpf")
    op.drop_column("clients", "nome")
    op.drop_column("clients", "tipo_pessoa")
    op.create_table(
        "fiscal_deadlines",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("deadline_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "is_global",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("fiscal_deadlines_pkey")),
    )
    op.create_index(
        op.f("ix_fiscal_deadlines_tenant_id"),
        "fiscal_deadlines",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###
